### ISSUE TITLE
Dark mode not working

### ISSUE THREAD

**Issue by razonyang** [hbstack/disqus#143]

**Comment by razonyang** [comment]
The problem is that, the text color is right on dark mode, however it's background color is not (doesn't inherit from the parent), have no solution for now, any resources are welcome.

**Comment by LITUATUI** [comment]
Does [this](https://help.disqus.com/en/articles/1717201-disqus-appearance-customizations) help?

**Comment by LITUATUI** [comment]
If I set the color scheme to light in Disqus options, at least the text is readable while using the website in dark mode.

![disqus-options](https://github.com/hbstack/disqus/assets/49299328/cbb05cb1-7667-4e73-851e-503eafe0e360)

**Comment by LITUATUI** [comment]
Maybe [this](https://raddinox.com/posts/hugo-theme-dark-mode-toggle-bootstrap-disqus-dark-mode-bug-fix/) is related.

**Comment by razonyang** [comment]
Thanks for the last reference, it works now, please upgrade this module to `v0.1.1`.
